# Imagen base de Python ligera
FROM python:3.9-slim

# Establecer directorio de trabajo
# Imagen base de Python ligera
FROM python:3.9-slim

# Establecer directorio de trabajo
WORKDIR /app

# Copiar los requerimientos e instalarlos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el script de inferencia y los artefactos (.joblib)
COPY inference.py .
COPY *.joblib .
COPY coordenadas_aus.csv .
COPY input.csv .

# Comando por defecto al correr el contenedor
CMD ["python", "inference.py", "input.csv"]